CREATE TABLE users (
user_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
username VARCHAR(255) NOT NULL,
password VARCHAR(64) NOT NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL);
CREATE TABLE tasks (task_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, title VARCHAR(255), description TEXT, date TIMESTAMP DEFAULT CURRENT_TIMESTAMP );
