CREATE TABLE users (
user_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
username VARCHAR(255) NOT NULL,
password VARCHAR(64) NOT NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL);
CREATE TABLE tasks (task_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
title VARCHAR(500) NOT NULL,
column INTEGER(1) NOT NULL,
user_id INTEGER NOT NULL);
